In [2]:
print("hello")

hello


In [3]:
x=2
y=4
c=x+y
print(c)

6


In [16]:
big=0
a=int(input("Enter first number"))
b=int(input("Enter Second number"))
c=int(input("Enter third number"))


if(a>b):
  print(a,"is largest than",b)
elif(b<c):
  print(b,"is smallest than ",c)
elif(c>b):
  print(c, "is greater than", b)
else:
  print(b, "is greater than" , c)
  

Enter first number8
Enter Second number7
Enter third number5
8 is largest than 7


In [32]:

# Recheck this code & improve: 
first = 0
second = 1
 
for i in range(20):
	next = first + second
	print(next, end=", ")
 
	first = second
	second = next

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584, 4181, 6765, 10946, 

In [18]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

2
(2, 3)
6
int64


In [0]:
# afternoon session:

#fibinacci series by function

def fibonacci(n):
  a=0
  b=1
  print(a)
  print(b)
  for i in range(1,n):
    c=a+b
    a=b
    b=c
    print(c)

In [35]:
lis=[9,5,6]
max=0
for i in lis:
  if i>max:
    max=i
print(max)

9


In [37]:
# find the reverse of list
a=[3,5,7,9]
b=[]
for i in range(len(a)-1,-1,-1):
  b.append(a[i])
print(b)

[9, 7, 5, 3]


In [38]:
# Fibbonacci series:
a=0
b=1
print(a)
print(b)
n=7
for i in range(1,n):
  c=a+b
  a=b
  b=c
  print(c)

0
1
1
2
3
5
8
13


In [0]:
def fibbonacci(n):
  a=0
  b=1
  print(a)
  print(b)
  n=7
  for i in range(1,n):
    c=a+b
    a=b
    b=c
    print(c)
  

In [40]:
fibbonacci(10)

0
1
1
2
3
5
8
13


In [41]:
vec1 = np.array([[1, 2],[1, 2],[1, 2]])
print(vec1)


[[1 2]
 [1 2]
 [1 2]]


In [42]:
vector = np.array([1, 2, 3, 4, 5, 6])
print(vector)

[1 2 3 4 5 6]


In [44]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
matrix[1][2]

6

In [48]:
matrix[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
matrix[:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
matrix[-1]

array([7, 8, 9])

In [52]:
matrix.shape
matrix.size
matrix.ndim

2

In [53]:
x = np.array( ((2,3), (3, 5)) )
y = np.matrix( ((1,2), (5, -1)) )
np.dot(x,y)

matrix([[17,  1],
        [28,  1]])

In [54]:
x = np.array([[1,2,3], [4,5,6]])
y = np.array([[4,5,6], [1,2,3]])
np.cross(x, y)

array([[-3,  6, -3],
       [ 3, -6,  3]])

In [61]:
import numpy as np 
  
# output array 
a = np.random.randint(low = 1, high = 9, size =(3, 3)) # Even if we dont say low & high it will work witout it
b = np.random.randint(low = 1, high = 9, size =(3, 3))
print(a)
print(b)


[[1 7 7]
 [7 4 4]
 [6 4 5]]
[[1 5 1]
 [8 8 6]
 [2 4 2]]


In [62]:
np.cross(a,b)

array([[-28,   6,  -2],
       [ -8, -10,  24],
       [-12,  -2,  16]])

In [63]:
np.dot(a,b)

array([[71, 89, 57],
       [47, 83, 39],
       [48, 82, 40]])

In [64]:
np.add(a,b)

array([[ 2, 12,  8],
       [15, 12, 10],
       [ 8,  8,  7]])

In [91]:
# Refreshment of python
# Strating with pandas
# reading csv file:
import pandas as pd
df=pd.read_csv("diabetes.csv") # uci machine learning repository
df[:5]
# df.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [0]:
# Creating a null value

In [117]:
# importing pandas as pd 
import pandas as pd 
  
# importing numpy as np 
import numpy as np 
  
# dictionary of lists 
dict = {'Maths':[100, 90, 87, 95], 
        'Physics': [30, 45, 56, np.nan], 
        'Chemistry':[np.nan, 40, 80, 98],
        'Index Title'  : ["A", "B", "C", "D"]
       } 

# creating a dataframe from list 
df = pd.DataFrame(dict) 
df.index = df["Index Title"] 
df
df2=df.drop('Index Title',axis=1)
df2

Maths  Physics  Chemistry
Index Title                           
A              100     30.0        NaN
B               90     45.0       40.0
C               87     56.0       80.0
D               95      NaN       98.0

In [118]:
# using isnull() function   
df2.isnull() 

Maths  Physics  Chemistry
Index Title                           
A            False    False       True
B            False    False      False
C            False    False      False
D            False     True      False

In [119]:
df2.dropna()

Maths  Physics  Chemistry
Index Title                           
B               90     45.0       40.0
C               87     56.0       80.0

In [122]:
df2.fillna(0)

Maths  Physics  Chemistry
Index Title                           
A              100     30.0        0.0
B               90     45.0       40.0
C               87     56.0       80.0
D               95      0.0       98.0

In [125]:
# filling rowwise mean to the null values
df2.fillna(df.mean(), axis=0)

Maths    Physics  Chemistry
Index Title                             
A              100  30.000000  72.666667
B               90  45.000000  40.000000
C               87  56.000000  80.000000
D               95  43.666667  98.000000

In [126]:
df2.fillna(df.mean())

Maths    Physics  Chemistry
Index Title                             
A              100  30.000000  72.666667
B               90  45.000000  40.000000
C               87  56.000000  80.000000
D               95  43.666667  98.000000

In [120]:
# Indexing:
# loc
# iloc

df.loc["A","Physics"]

30.0

In [121]:
df.iloc[1,2]

40.0

In [0]:
# concat does merging on axis
# ignore index
# create two dataframe 
# concat on axis=1
# try ignore index


In [0]:
a = pd.read_csv("1.csv")
b = pd.read_csv("2.csv")

In [128]:
a

Id  Q1  Q2  Q3  Q4
0   1   1  -1   1   8
1   2   3  -1   1   4
2   3  10   3   2   6
3   4   9  -1  10  10

In [129]:
b

Id  Q1  Q2  Q3  Q4
0  1277  10  10   4   6
1  1278   2  -1   5   4
2  1279   2  -1   4   5
3  1280   1  -1   2   3

In [130]:
pd.concat([a,b])

Id  Q1  Q2  Q3  Q4
0     1   1  -1   1   8
1     2   3  -1   1   4
2     3  10   3   2   6
3     4   9  -1  10  10
0  1277  10  10   4   6
1  1278   2  -1   5   4
2  1279   2  -1   4   5
3  1280   1  -1   2   3

In [0]:
pd.concat([a,b],axis=1, join='outer', join_axes=None, ignore_index=False)